// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtBqJVLxAoMI1edRvT8Hy2WCH2Ney_56A',
    appId: '1:796219209312:web:198133641e50f40ea9f505',
    messagingSenderId: '796219209312',
    projectId: 'duogle2803',
    authDomain: 'duogle2803.firebaseapp.com',
    storageBucket: 'duogle2803.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCmnReQCD9YWTAhk5G1oBsdOc24luc3g',
    appId: '1:796219209312:android:436d40ed5cfcd6efa9f505',
    messagingSenderId: '796219209312',
    projectId: 'duogle2803',
    storageBucket: 'duogle2803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWKK8G8I97ZTTrzf52ScgStxbsdB-Cok',
    appId: '1:796219209312:ios:4be61b21fa3505efa9f505',
    messagingSenderId: '796219209312',
    projectId: 'duogle2803',
    storageBucket: 'duogle2803.appspot.com',
    iosBundleId: 'com.example.f2FlutterEcommerceApp',
  );
}
